### ISSUE TITLE
Fix compute and graphics queue family index selection

### ISSUE THREAD

**Issue by SaschaWillems** [AndreasReiten/qtvknbody#2]
I'm currently trying to get this working on an AMD GPU and the first thing that needs fixing is the queue family selection.

[In this line](https://github.com/AndreasReiten/qtvknbody/blob/master/vulkanbase.cpp#L360) the queue selection code checks if there is a queue family with a queue count of at least two that supports transfer, graphics or compute. On AMD GPUs (see [this hardware report](http://vulkan.gpuinfo.org/displayreport.php?id=612#queuefamilies)) this results in family index 1 being selected for graphics and compute, while that family only supports graphics.

Ideally you'd store separate family indices for graphics and compute to cope with the different queue families available for different GPUs. 

While not perfect I recently added such code to my [VulkanDevice class](https://github.com/SaschaWillems/Vulkan/blob/master/base/vulkandevice.hpp). It will find queue family indices for graphics and compute and if there is a family that supports compute but not graphics then it'll use it's index for the compute family (as that's most likely a dedicated compute queue with async capability). Not perfect, but sufficient for most cases.

Note that if you're running with different queue family indices for graphics and compute you'll have to set the srcQueueFamilyIndex and dstQueueFamilyIndex of your barriers accordingly.

I'm a bit short on time currently, and don't know when or if I could do a PR for this, but I hope my explanation helps.

**Comment by AndreasReiten** [comment]
Thanks! I am quite new to Github and did not notice the issue popping up. I'll look at this shortly.

**Comment by JoMazM** [comment]
Nice work Andreas,

I tried to run the demo but I'm getting the following errors right after the application starts.

[DS] Invalid Pipeline CreateInfo State: pDepthStencilState is NULL when rasterization is enabled and subpass uses a depth/stencil attachment. For more information refer to Vulkan Spec Section '9.2. Graphics Pipelines' which states 'If the rasterizerDiscardEnable member of pRasterizationState is VK_FALSE, and subpass uses a depth/stencil attachment, pDepthStencilState must be a pointer to a valid VkPipelineDepthStencilStateCreateInfo structure' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkPipelineCreateFlagBits) (2115)
WARNING [DS] In vkCmdBeginRenderPass() the VkRenderPassBeginInfo struct has a clearValueCount of 3 but only first 2 entries in pClearValues array are used. The highest index of any attachment in renderPass 0x10 that uses VK_ATTACHMENT_LOAD_OP_CLEAR is 1 - other pClearValues are ignored. (52)
WARNING [DS] In vkCmdBeginRenderPass() the VkRenderPassBeginInfo struct has a clearValueCount of 3 but only first 2 entries in pClearValues array are used. The highest index of any attachment in renderPass 0x10 that uses VK_ATTACHMENT_LOAD_OP_CLEAR is 1 - other pClearValues are ignored. (52)
WARNING [DS] In vkCmdBeginRenderPass() the VkRenderPassBeginInfo struct has a clearValueCount of 3 but only first 2 entries in pClearValues array are used. The highest index of any attachment in renderPass 0x10 that uses VK_ATTACHMENT_LOAD_OP_CLEAR is 1 - other pClearValues are ignored. (52)
[DS] In vkCmdBeginRenderPass() the VkRenderPassBeginInfo struct has a clearValueCount of 3 but only first 2 entries in pClearValues array are used. The highest index of any attachment in renderPass 0x10 that uses VK_ATTACHMENT_LOAD_OP_CLEAR is 1 - other pClearValues are ignored. (52)
WARNING [DS] In vkCmdBeginRenderPass() the VkRenderPassBeginInfo struct has a clearValueCount of 3 but only first 2 entries in pClearValues array are used. The highest index of any attachment in renderPass 0x10 that uses VK_ATTACHMENT_LOAD_OP_CLEAR is 1 - other pClearValues are ignored. (52)
WARNING [DS] In vkCmdBeginRenderPass() the VkRenderPassBeginInfo struct has a clearValueCount of 3 but only first 2 entries in pClearValues array are used. The highest index of any attachment in renderPass 0x10 that uses VK_ATTACHMENT_LOAD_OP_CLEAR is 1 - other pClearValues are ignored. (52)
ERROR [DS] Unable to allocate 1 descriptors of type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER from pool 0x8c. This pool only has 0 descriptors of this type remaining. For more information refer to Vulkan Spec Section '13.2.3. Allocation of Descriptor Sets' which states 'descriptorPool must have enough free descriptor capacity remaining to allocate the descriptor sets of the specified layouts' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkDescriptorSetAllocateInfo) (912)
WARNING [DS] In vkCmdBeginRenderPass() the VkRenderPassBeginInfo struct has a clearValueCount of 3 but only first 2 entries in pClearValues array are used. The highest index of any attachment in renderPass 0x10 that uses VK_ATTACHMENT_LOAD_OP_CLEAR is 1 - other pClearValues are ignored. (52)
WARNING [DS] In vkCmdBeginRenderPass() the VkRenderPassBeginInfo struct has a clearValueCount of 3 but only first 2 entries in pClearValues array are used. The highest index of any attachment in renderPass 0x10 that uses VK_ATTACHMENT_LOAD_OP_CLEAR is 1 - other pClearValues are ignored. (52)
WARNING [DS] In vkCmdBeginRenderPass() the VkRenderPassBeginInfo struct has a clearValueCount of 3 but only first 2 entries in pClearValues array are used. The highest index of any attachment in renderPass 0x10 that uses VK_ATTACHMENT_LOAD_OP_CLEAR is 1 - other pClearValues are ignored. (52)
ERROR [DS] Unable to allocate 1 descriptorSets from pool 0x8c. This pool only has 0 descriptorSets remaining. For more information refer to Vulkan Spec Section '13.2.3. Allocation of Descriptor Sets' which states 'descriptorSetCount must not be greater than the number of sets that are currently available for allocation in descriptorPool' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkDescriptorSetAllocateInfo) (911)
WARNING [ParameterValidation] vkAllocateDescriptorSets: returned VK_ERROR_OUT_OF_DEVICE_MEMORY, indicating that a device memory allocation has failed (9)
VK_RESULT [line 4076 in ..\qtvknbody\vulkanwindow.cpp] VK_ERROR_OUT_OF_DEVICE_MEMORY (vkAllocateDescriptorSets(vkbase.device(), &allocate_info, &descriptor_leapgfrog))
nbody.exe exited with code 255


The first frame is drawn though. It may be the case that my GPU does not have enough memory
I'm using a GTX 950
"devicename":"GTX 950","devicetype":"DISCRETE_GPU","driverversion":"376.53.0.0"
